os:
  edit: 'tmux split-window -h "hx {{filename}}"'
  editAtLine: 'tmux split-window -h "hx {{filename}}:{{line}}"'
  editAtLineAndWait: 'tmux split-window -h "hx {{filename}}:{{line}}"'
  editInTerminal: false
